name: eda_automated

on: push

jobs: 

  name : eda_autamed
  runs-on : unbuntu-latest

  steps:
    - name : create eda code
      users : github/AbhishekMonarchEmmanual
      env:
        DEFAULT_BRANCH : main




